### ISSUE TITLE
Aptly – Debian repository management

### ISSUE THREAD

**Issue by n1trux** [awesome-foss/awesome-sysadmin#193]
idk where to put this. Does anybody have an idea?

https://www.aptly.info/

> aptly is a swiss army knife for Debian repository management: it allows you to mirror remote repositories, manage local package repositories, take snapshots, pull new versions of packages along with dependencies, publish as Debian repository. You can try it right now just for free.
> 
> aptly is available both as CLI tool and HTTP REST service.

**Comment by nodiscc** [comment]
https://github.com/n1trux/awesome-sysadmin#deployment-automation ?

**Comment by ardichoke** [comment]
Deployment Automation is probably the closest fit currently... my only other thought would be to change the "Packaging" section to "Packaging & Package Management" and put it there.
