### ISSUE TITLE
add Technitium DNS

### ISSUE THREAD

**Issue by nothead31** [awesome-foss/awesome-sysadmin#382]
[Technitium DNS](https://technitium.com/dns/)

Flexible and functional alternative to Pi-hole and Unbound, Technitium is lightweight enough to run on an RPi (I run an instance on an RPi 4B) and has the capacity to operate as an authoritative NS. Can be installed as a pre-configured pacakge, from source, or in a docker container.

[Licensed under GPL3](https://github.com/TechnitiumSoftware/DnsServer/blob/master/LICENSE)

**Comment by Rabenherz112** [comment]
The DNS Server has already been added in awesome-selfhosted.
https://github.com/awesome-selfhosted/awesome-selfhosted/#dns
