### ISSUE TITLE
Add proxmox backup server

### ISSUE THREAD

**Issue by ranomier** [awesome-foss/awesome-sysadmin#398]
Proxmox backup server was mainly made for for the proxmox virtual environment, but...

There is the proxmox-backup-client which is just a command line utility and you can backup from anywhere :)

https://www.proxmox.com/en/proxmox-backup-server

https://pbs.proxmox.com/docs/backup-client.html

**Comment by nodiscc** [comment]
https://github.com/awesome-foss/awesome-sysadmin/pull/494
