### ISSUE TITLE
Remote management: add TightVNC, RustDesk, FreeRDP

### ISSUE THREAD

**Issue by G2G2G2G** [awesome-foss/awesome-sysadmin#404]
You have tigervnc, which is worse in every way, so I assume you want https://www.tightvnc.com/ on your list of remote management

rust desk is also easier/better than both if you're running your own infrastructure https://github.com/rustdesk/rustdesk

and there also is https://github.com/FreeRDP/FreeRDP

**Comment by nodiscc** [comment]
See https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3327

>  https://github.com/awesome-foss/awesome-sysadmin#remote-management and https://github.com/awesome-selfhosted/awesome-selfhosted#remote-access could be reorganized.

In the mean time feel free to send Pull Request to add the projects you mentioned. Servers should go to https://github.com/awesome-selfhosted/awesome-selfhosted#remote-access, clients and related software should go to https://github.com/awesome-foss/awesome-sysadmin#remote-management

**Comment by G2G2G2G** [comment]
So you want me to delete tight vnc from here as well and move it to that one?

what do we do with software that offers clients + servers, stand alone servers, and stand alone clients like tightvnc does?

**Comment by G2G2G2G** [comment]
rustdesk has their own server you can run (for negotiating and routing of the people connecting to each other), and the program is a client/server for the specific PC it's installed on for access.

Not sure where to add it other than both places.

Something like Remmina is pretty straight forward because it just connects to stuff

**Comment by cdpb** [comment]
I would merge everything under *remote access* and maybe have a sub header for client, server and mixed or something.

**Comment by G2G2G2G** [comment]
Yea he has these spread on two entirely different repos though

**Comment by nodiscc** [comment]
- Remote desktop clients are now listed under https://github.com/awesome-foss/awesome-sysadmin/tree/master#remote-desktop-clients
- Remote desktop servers and web clients/interfaces are now listed under https://github.com/awesome-selfhosted/awesome-selfhosted#remote-access
- Rustdesk is already listed there
- Please submit separate issues for FreeRDP and TightVNC
