### ISSUE TITLE
wrong URL for lime text

### ISSUE THREAD

**Issue by G2G2G2G** [awesome-foss/awesome-sysadmin#406]
https://limetext.github.io/ it was never the website you link in the readme, it was always this github one

**Comment by nodiscc** [comment]
A Pull Request was sent at https://github.com/awesome-foss/awesome-sysadmin/pull/410. But the project is abandoned, so Isuggest removing it completely. Closing, followup in https://github.com/awesome-foss/awesome-sysadmin/pull/410
