### ISSUE TITLE
Add Ory softwares

### ISSUE THREAD

**Issue by germainlefebvre4** [awesome-foss/awesome-sysadmin#428]
Ory open source IAM suites.

Identity Management:
* Kratos: https://www.ory.sh/docs/kratos/ory-kratos-intro

OAuth2 & OpenID Connect:
* Hydra: https://www.ory.sh/docs/hydra/

**Comment by nodiscc** [comment]
https://github.com/awesome-foss/awesome-sysadmin/pull/420
