### ISSUE TITLE
DNS Section missing TechnitiumDNS

### ISSUE THREAD

**Issue by Sysadminfromhell** [awesome-foss/awesome-sysadmin#500]
I think the list is missing the DNS Server TechnitiumDNS.

https://technitium.com/dns/

You can have your own Zones and DNS Blacklisting / DNS Blocking like Pi-Hole.
Also supports Clustering with Apps and has an  AppStore for 3rd Party App Developer, you can also write your own once.
DHCP and DDNS is there since 9.1 also so with pfSense or other Firewalls it works if the DHCP is foreign.
I use 2 in my own Home.

**Comment by nodiscc** [comment]
- https://github.com/awesome-foss/awesome-sysadmin/pull/492
- https://github.com/awesome-selfhosted/awesome-selfhosted/#dns
