### ISSUE TITLE
Interested in listing Feature Flagging solution

### ISSUE THREAD

**Issue by thomaspoignant** [awesome-foss/awesome-sysadmin#534]
I would like to know if you could be interested in adding a section for feature flagging solutions?
If not under which category do you think it should be?

**Comment by nodiscc** [comment]
Hi @thomaspoignant, feature flagging software is currently listed at https://github.com/awesome-selfhosted/awesome-selfhosted#miscellaneous. We don't allow duplicates between the two lists to prevent duplication of effort.

**Comment by thomaspoignant** [comment]
@nodiscc got it, I close the issue.
